#!/usr/bin/env bash

if [[ -s "/home/action/.rvm/environments/ruby-2.0.0-p247@rails-bootstrap" ]]
then
  source "/home/action/.rvm/environments/ruby-2.0.0-p247@rails-bootstrap"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/environments/ruby-2.0.0-p247@rails-bootstrap'" >&2
  exit 1
fi
