#!/usr/bin/env bash

if [[ -s "/home/action/.rvm/environments/ruby-2.0.0-p247@railstutorial_rails_4_0" ]]
then
  source "/home/action/.rvm/environments/ruby-2.0.0-p247@railstutorial_rails_4_0"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/environments/ruby-2.0.0-p247@railstutorial_rails_4_0'" >&2
  exit 1
fi
